# Generated by Django 5.2.3 on 2025-07-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.CharField(
                choices=[
                    ("repair", "Fix & Repair"),
                    ("personal_help", "Personal Help"),
                    ("delivery", "Move & Deliver"),
                ],
                max_length=30,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="material_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Extra cost for parts/materials, if applicable",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="photo_urls",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of photo URLs related to the job",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True,
                help_text="Specific date and time the task is scheduled for",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="subcategory",
            field=models.CharField(
                blank=True, help_text="Subcategory or specific task type", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("confirmed", "Confirmed"),
                    ("in-progress", "In-Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
