# Generated by Django 5.2.3 on 2025-06-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_client",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_worker",
        ),
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("worker", "Worker"), ("client", "Client")],
                default="client",
                max_length=20,
            ),
        ),
    ]
