# Generated by Django 5.2.3 on 2025-06-22 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_is_client_remove_user_is_worker_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="accept_bids",
        ),
        migrations.RemoveField(
            model_name="job",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_completed",
        ),
        migrations.RemoveField(
            model_name="job",
            name="suggested_budget",
        ),
        migrations.AddField(
            model_name="job",
            name="budged",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs_posted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="location",
            field=models.CharField(max_length=255),
        ),
    ]
