# Generated by Django 5.2.3 on 2025-07-10 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_subtask_tasker_task_finished_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="tasker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subtasks_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
