# Generated by Django 5.2.3 on 2025-07-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_job_category_job_material_cost_job_photo_urls_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("repair", "Fix & Repair"),
                    ("personal_help", "Personal Help"),
                    ("delivery", "Move & Deliver"),
                ],
                default=None,
                max_length=30,
                null=True,
            ),
        ),
    ]
