# Generated by Django 5.2.3 on 2025-07-10 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_subtask_tasker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="termsacceptancelog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tsc_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
