# Generated by Django 5.2.3 on 2025-06-22 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_job_accept_bids_remove_job_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="budged",
            new_name="budget",
        ),
    ]
