# Generated by Django 5.2.3 on 2025-07-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_adminlog"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AdminLog",
            new_name="TaskLog",
        ),
    ]
