# Generated by Django 5.2.3 on 2025-06-22 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_job_worker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="worker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs_done",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
