# Generated by Django 5.2.3 on 2025-07-12 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_adminlog_tasklog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="finished_at",
            new_name="completed_at",
        ),
        migrations.AddField(
            model_name="tasklog",
            name="task_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="task_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasklog_task_client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="task_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="task_finished_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="task_tasker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasklog_task_tasker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tasks_created", "Tasks Created"),
                    ("tasks_completed", "Tasks Completed"),
                    ("tasks_cancelled", "Tasks Cancelled"),
                    ("user_login", "User Login"),
                ],
                max_length=50,
            ),
        ),
    ]
