# Generated by Django 5.2.3 on 2025-06-23 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_job_cancelled_alter_job_worker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="cancelled",
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted", "accepted"),
                    ("inprogress", "In Progress"),
                    ("completed", "Completed"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
