# Generated by Django 5.2.3 on 2025-07-12 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_finished_at_task_completed_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_finished_at",
            new_name="task_completed_at",
        ),
    ]
