# Generated by Django 5.2.3 on 2025-06-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_remove_job_cancelled_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("now", "Now - 5 minutes"),
                    ("soon", "Soon - 30 minutes"),
                    ("flexible", "Later - 1 hour"),
                ],
                default="soon",
                max_length=20,
            ),
        ),
    ]
