# Generated by Django 5.2.3 on 2025-07-13 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_rename_task_finished_at_tasklog_task_completed_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasklog",
            name="details",
        ),
        migrations.RemoveField(
            model_name="tasklog",
            name="task_category",
        ),
        migrations.AddField(
            model_name="tasklog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="task_budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="task_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="task_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tasklog",
            name="terms_accepted_client_at",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasklogs_terms_client",
                to="api.termsacceptancelog",
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("tasks_created", "Tasks Created"),
                    ("tasks_completed", "Tasks Completed"),
                    ("tasks_cancelled", "Tasks Cancelled"),
                    ("user_login", "User Login"),
                    ("terms_accepted_client_at", "Terms Accepted By Client"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="task_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasklogs_as_client",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tasklog",
            name="task_tasker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasklogs_as_tasker",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
