# Generated by Django 5.2.3 on 2025-07-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_remove_tasklog_details_remove_tasklog_task_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("repair", "Fix & Repair"),
                    ("personal_help", "Personal Help"),
                    ("delivery", "Move & Deliver"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="eta",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="profile",
            name="family_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="tasks_done",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in-progress", "In-Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
