# Generated by Django 5.2.3 on 2025-06-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_job_urgency"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="expires_from_feed",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="job",
            name="must_start_by",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="job",
            name="urgency",
            field=models.CharField(
                choices=[
                    ("now", "Now - 5 minutes"),
                    ("soon", "Soon - 30 minutes"),
                    ("flexible", "Later - 1 hour"),
                ],
                default="now",
                max_length=20,
            ),
        ),
    ]
