# Generated by Django 5.2.3 on 2025-06-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_job_expires_from_feed_job_must_start_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted", "accepted"),
                    ("in-progress", "In-Progress"),
                    ("completed", "Completed"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
