# Generated by Django 5.2.3 on 2025-07-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_profile_category_profile_eta_profile_family_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("repair", "Fix & Repair"),
                    ("personal_help", "Personal Help"),
                    ("delivery", "Move & Deliver"),
                    ("other", "Other"),
                ],
                default="repair",
                max_length=30,
            ),
        ),
    ]
