# Generated by Django 5.2.3 on 2025-07-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_profile_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="tasks_posted",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
