# Generated by Django 5.2.3 on 2025-06-24 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 24, 10, 58, 22, 516413, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="expires_from_feed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="must_start_by",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
