# Generated by Django 5.2.3 on 2025-06-24 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_job_created_at_job_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 24, 11, 6, 16, 19138, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
