# Generated by Django 5.2.3 on 2025-07-14 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_profile_tasks_posted"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="requests",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of incoming tasker requests with tasker ID, rating, ETA, etc.",
            ),
        ),
        migrations.CreateModel(
            name="TaskRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eta", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.task"
                    ),
                ),
                (
                    "tasker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
