# Generated by Django 5.2.3 on 2025-07-15 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_task_requests_taskrequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskrequest",
            name="eta",
        ),
    ]
