# Generated by Django 5.2.3 on 2025-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_remove_taskrequest_eta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("accepted", "Accepted by Client"),
                    ("confirmed", "Confirmed by Tasker"),
                    ("in-progress", "In-Progress"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
