# Generated by Django 5.2.3 on 2025-07-18 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_taskchatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks_posted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
