# Generated by Django 5.2.3 on 2025-07-18 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_alter_task_client"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_budget",
            new_name="budget",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_client",
            new_name="client",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_completed_at",
            new_name="completed_at",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_created_at",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_tasker",
            new_name="tasker",
        ),
        migrations.RenameField(
            model_name="tasklog",
            old_name="task_title",
            new_name="title",
        ),
    ]
