# Generated by Django 5.2.3 on 2025-07-18 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_rename_task_budget_tasklog_budget_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrequest",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_requests_posted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="taskrequest",
            name="tasker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_requests_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
