# Generated by Django 5.2.3 on 2025-06-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_job_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="updated_at",
        ),
    ]
