# Generated by Django 5.2.3 on 2025-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_taskrequest_client_alter_taskrequest_tasker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="eta",
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
