# Generated by Django 5.2.3 on 2025-07-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_profile_eta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="eta",
            field=models.IntegerField(default=0),
        ),
    ]
