# Generated by Django 5.2.3 on 2025-06-24 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_job_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
