# Generated by Django 5.2.3 on 2025-07-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_alter_profile_eta"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskrequest",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
