# Generated by Django 5.2.3 on 2025-06-24 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_alter_job_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 24, 13, 9, 15, 510946, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
