# Generated by Django 5.2.3 on 2025-06-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_job_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
