# Generated by Django 5.2.3 on 2025-06-24 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_job_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
