"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s$-wy3b3(mhjxzzftu^$d3e!b1zi^y6&qfo0e@c2z&z0nxrn&e"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # SHORT lifespan
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,  # Optional: rotates refresh token on use
    "BLACKLIST_AFTER_ROTATION": True,  # Optional: blacklist old refresh tokens
    "AUTH_HEADER_TYPES": ("Bearer",),
}


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "api",
    "corsheaders",
    "channels",
    "rest_framework_simplejwt.token_blacklist",
    "django_celery_beat",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


ASGI_APPLICATION = "config.asgi.application"

redis_host = os.getenv("REDIS_HOST", "127.0.0.1")


CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/1"


CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "api.User"

CORS_ALLOW_ALL_ORIGINS = True  # Temporarily for dev (later restrict by origin)

CURRENT_TSC_VERSION = "v1.0"
CURRENT_TSC_TEXT = f"""
 TERMENI ȘI CONDIȚII - PLATFORMĂ TASKOON, versiunea tsc {CURRENT_TSC_VERSION}

1. Părțile implicate

Platforma Taskoon (deținută de [Numele companiei], numită în continuare „Platforma”) oferă un serviciu digital care intermediază prestarea de servicii între două părți:

Clientul - persoana fizică sau juridică care comandă un serviciu prin aplicație;
Taskerul - prestatorul de servicii, persoană fizică independentă, care acceptă comanda și prestează efectiv serviciul.

2. Natura serviciului

Platforma:

* Asigură interfața de legătură între Client și Tasker;
* Colectează plata integrală de la Client;
* Reține un comision de 30%;
* Transferă 70% din sumă către Tasker după confirmarea prestării serviciului.

Platforma nu este parte în prestația efectivă a serviciului, ci doar intermediază.

3. Acceptarea condițiilor și a contractelor

Prin utilizarea aplicației și bifarea căsuței „Sunt de acord cu Termenii și Condițiile”, utilizatorii (atât Clientul, cât și Taskerul):

* Declară că au citit, înțeles și acceptat toate regulile, drepturile și obligațiile prevăzute în Termenii și Condițiile platformei;
* își asumă implicit toate clauzele contractelor semnate sau acceptate electronic între Platformă și ei, respectiv:

  * Contractul de prestare servicii între Platformă și Tasker,
  * Contractul de furnizare servicii între Platformă și Client.

Această acceptare prin click are valoare juridică egală cu semnătura electronică, fiind suficientă pentru validarea relației contractuale.

4. Relația juridică

* Taskerul nu este angajat al platformei. Este un prestator independent de servicii (persoană fizică).
* Clientul este beneficiar direct al serviciului prestat de Tasker.
* Platforma nu răspunde pentru calitatea serviciului prestat, ci doar facilitează tranzacția.

5. Plata și impozitele

* Clientul achită integral serviciul în aplicație (ex: 1000 lei).
* Platforma reține 30% comision (ex: 300 lei).
* Taskerul primește 70% (ex: 700 lei).
* **Din suma achitată Taskerului, Platforma reține 12% impozit pe venit conform Codului fiscal art. 90¹**, dacă Taskerul nu deține statut de întreprindere.
* Taskerul nu are obligația de a prezenta chitanță sau factură, dar trebuie să accepte electronic în aplicație că a prestat serviciul.

Exemplu: din 1000 lei achitați de client, taskerul primește 700 - 12% = 616 lei net; impozitul de 84 lei este achitat de platformă în numele lui. Platforma achită impozitul și pentru comisionul ei.

6. Confirmarea serviciului

* După efectuarea serviciului, Taskerul va confirma electronic că a prestat serviciul (semnătură digitală sau buton de confirmare în aplicație).
* Această confirmare declanșează transferul sumei către Tasker.

7. Răspundere și limitări

* Taskerul este singurul responsabil pentru calitatea și siguranța serviciului prestat.
* Clientul are obligația de a furniza informații corecte.
* Platforma poate media conflictele, dar nu are obligații contractuale privind execuția serviciului.

8. Fiscalitate

* Taskerul este informat că Platforma acționează ca plătitor al impozitului reținut la sursă (12% din suma brută), în numele lui.
* Platforma poate elibera dovadă de reținere a impozitului, la cerere.
* Platforma achită impozitul propriu pentru comisionul reținut (30%), conform legislației în vigoare.

9. Protecția datelor

Platforma colectează și procesează date personale conform Legii 133/2011 privind protecția datelor. Datele nu sunt partajate fără consimțământ și sunt folosite strict pentru operarea platformei.

10. Modificări

Platforma își rezervă dreptul de a modifica Termenii și Condițiile. Orice modificare va fi publicată pe site și în aplicație. Continuarea utilizării constituie acceptarea modificărilor.

11. Interdicții și utilizare abuzivă

11.1. Este **strict interzisă** folosirea platformei Taskoon în scopuri ilegale, abuzive sau contrare ordinii publice, inclusiv, dar fără a se limita la:

* Solicitarea sau oferirea de servicii cu caracter sexual (inclusiv prostituție);
* Trafic de persoane;
* Exploatarea prin muncă a minorilor sau persoanelor vulnerabile;
* Orice activitate care încalcă legislația Republicii Moldova.

11.2. **Platforma nu răspunde sub nicio formă pentru prejudicii directe sau indirecte cauzate de utilizatori care se angajează în activități ilegale**. Răspunderea pentru faptele ilegale revine exclusiv persoanei care le comite.

11.3. În cazul în care Platforma identifică sau primește notificări privind activități suspecte, își rezervă dreptul de a:

* suspenda sau șterge conturile implicate, fără preaviz;
* bloca transferurile de fonduri aferente taskului respectiv;
* notifica autoritățile competente, conform obligațiilor legale.
"""


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # or DEBUG
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
